import asyncio
import glob
import os
import re
import time
import threading
import json
from datetime import datetime
from typing import Any, Dict, List, Optional, Set

import pandas as pd
from fastapi import FastAPI, HTTPException, Query, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field


LOG_BASE_DIR = os.path.normpath(os.getenv("BOOKING_LOG_DIR", "logs"))
PC_STATE_CSV = os.path.join(LOG_BASE_DIR, "pc_state_all.csv")
PERF_SUMMARY_CSV = os.path.join(LOG_BASE_DIR, "performance_summary.csv")
USER_ID_STATE_FILE = os.path.join(LOG_BASE_DIR, "user_id_state.json")

PEOPLE_GLOB = os.path.join(LOG_BASE_DIR, "*", "people_with_conf_and_roi_*_*.csv")
PC_ACTIVITY_GLOB = os.path.join(LOG_BASE_DIR, "*", "pc_activity_events_*_*.csv")
UNATTENDED_GLOB = os.path.join(LOG_BASE_DIR, "pc_unattended_flags_*.csv")

DAY_TAG_PATTERN = re.compile(r"_(\d{8})\.csv$", re.IGNORECASE)
USER_ID_10_DIGIT_PATTERN = re.compile(r"^\d{10}$")


app = FastAPI(
    title="Booking Log API",
    description="Serves camera/PC logs generated by threaded.py to local booking systems.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


class UserIdIssueRequest(BaseModel):
    source: Optional[str] = None
    preferred_user_id: Optional[str] = None


class UserIdIssueResponse(BaseModel):
    user_id: str
    strategy: str
    issued_at: str
    source: Optional[str] = None


class UserIdPoolUpdateRequest(BaseModel):
    user_ids: List[str] = Field(default_factory=list)
    replace: bool = False


class UserIdPoolUpdateResponse(BaseModel):
    pool_size: int
    accepted_count: int
    replaced: bool


USER_ID_STATE_LOCK = threading.Lock()
USER_ID_STATE: Dict[str, Any] = {
    "pool": [],
    "issued": [],
}


def clean_user_id(value: Any) -> Optional[str]:
    text = str(value or "").strip()
    if not text:
        return None
    return text if USER_ID_10_DIGIT_PATTERN.fullmatch(text) else None


def ensure_log_dir_exists() -> None:
    os.makedirs(LOG_BASE_DIR, exist_ok=True)


def load_user_id_state() -> None:
    ensure_log_dir_exists()
    if not os.path.exists(USER_ID_STATE_FILE):
        return

    try:
        with open(USER_ID_STATE_FILE, "r", encoding="utf-8") as state_file:
            loaded = json.load(state_file) or {}
        if isinstance(loaded, dict):
            pool = loaded.get("pool", [])
            issued = loaded.get("issued", [])
            USER_ID_STATE["pool"] = [str(x) for x in pool if clean_user_id(x)]
            USER_ID_STATE["issued"] = [str(x) for x in issued if clean_user_id(x)]
    except Exception as exc:
        print(f"Warning: failed to load user ID state: {exc}")


def save_user_id_state() -> None:
    ensure_log_dir_exists()
    try:
        with open(USER_ID_STATE_FILE, "w", encoding="utf-8") as state_file:
            json.dump(USER_ID_STATE, state_file, ensure_ascii=True, indent=2)
    except Exception as exc:
        print(f"Warning: failed to save user ID state: {exc}")


def issue_user_id(preferred_user_id: Optional[str]) -> Dict[str, str]:
    preferred_raw = str(preferred_user_id).strip() if preferred_user_id is not None else ""
    preferred = clean_user_id(preferred_raw)
    if preferred_raw and not preferred:
        raise HTTPException(status_code=400, detail="preferred_user_id must be exactly 10 digits")

    if preferred:
        user_id = preferred
        strategy = "preferred"
    elif USER_ID_STATE.get("pool"):
        user_id = str(USER_ID_STATE["pool"].pop(0))
        strategy = "pool"
    else:
        raise HTTPException(status_code=409, detail="No user ID available. Please preload /api/user-ids/pool.")

    USER_ID_STATE.setdefault("issued", []).append(user_id)
    return {"user_id": user_id, "strategy": strategy}


load_user_id_state()


def normalize_label(value: Any) -> str:
    text = str(value or "").strip()
    cleaned = "".join((c if c.isalnum() or c in ("-", "_") else "_") for c in text)
    while "__" in cleaned:
        cleaned = cleaned.replace("__", "_")
    return cleaned.strip("_").lower()


def parse_date_to_day_tag(date_value: Optional[str]) -> Optional[str]:
    if date_value is None:
        return None

    text = str(date_value).strip()
    if not text:
        return None

    if re.fullmatch(r"\d{8}", text):
        return text

    try:
        return datetime.strptime(text, "%Y-%m-%d").strftime("%Y%m%d")
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid date format. Use YYYY-MM-DD or YYYYMMDD.")


def day_tag_to_iso(day_tag: str) -> str:
    if not re.fullmatch(r"\d{8}", str(day_tag or "")):
        return str(day_tag or "")
    return f"{day_tag[0:4]}-{day_tag[4:6]}-{day_tag[6:8]}"


def extract_day_tag(file_path: str) -> Optional[str]:
    match = DAY_TAG_PATTERN.search(os.path.basename(file_path))
    return match.group(1) if match else None


def read_csv_safe(file_path: str) -> pd.DataFrame:
    if not os.path.exists(file_path):
        return pd.DataFrame()

    try:
        return pd.read_csv(file_path)
    except pd.errors.EmptyDataError:
        return pd.DataFrame()
    except Exception as exc:
        print(f"Warning: Failed to read CSV {file_path}: {exc}")
        return pd.DataFrame()


def records_from_df(df: pd.DataFrame) -> List[Dict[str, Any]]:
    if df.empty:
        return []
    cleaned_df = df.where(pd.notnull(df), None)
    return cleaned_df.to_dict(orient="records")


def coerce_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    if isinstance(value, (int, float)):
        return bool(int(value))
    text = str(value).strip().lower()
    return text in {"1", "true", "yes", "on"}


def pc_name_sort_key(pc_name: Any):
    text = str(pc_name or "")
    digits = "".join(ch for ch in text if ch.isdigit())
    number = int(digits) if digits else 10**9
    return number, text


def filter_files(glob_pattern: str, camera: Optional[str], day_tag: Optional[str]) -> List[str]:
    camera_filter = normalize_label(camera) if camera else None
    files = sorted(path for path in glob.glob(glob_pattern) if os.path.isfile(path))
    matched = []

    for file_path in files:
        if day_tag:
            file_day_tag = extract_day_tag(file_path)
            if file_day_tag != day_tag:
                continue

        if camera_filter:
            parent_label = normalize_label(os.path.basename(os.path.dirname(file_path)))
            if parent_label != camera_filter:
                continue

        matched.append(file_path)

    return matched


def load_pc_status_rows() -> List[Dict[str, Any]]:
    df = read_csv_safe(PC_STATE_CSV)
    if df.empty:
        return []

    if "availble" in df.columns and "available" not in df.columns:
        df = df.rename(columns={"availble": "available"})

    for col_name, default_value in (("pc_name", ""), ("pc_on", False), ("available", 0)):
        if col_name not in df.columns:
            df[col_name] = default_value

    rows = []
    for _, row in df.iterrows():
        available_num = pd.to_numeric(row.get("available"), errors="coerce")
        available_value = 0 if pd.isna(available_num) else int(available_num)
        rows.append(
            {
                "pc_name": str(row.get("pc_name", "")),
                "pc_on": coerce_bool(row.get("pc_on")),
                "available": available_value,
            }
        )

    rows.sort(key=lambda item: pc_name_sort_key(item.get("pc_name")))
    return rows


def apply_time_sort_and_limit(df: pd.DataFrame, limit: int) -> pd.DataFrame:
    if "time" in df.columns:
        df = df.sort_values(by="time", ascending=False)
    if limit > 0:
        df = df.head(limit)
    return df


@app.get("/")
def root() -> Dict[str, Any]:
    return {
        "service": "booking-log-api",
        "log_base_dir": LOG_BASE_DIR,
        "endpoints": [
            "/api/pc-status",
            "/api/user-ids/issue",
            "/api/user-ids/pool",
            "/ws/pc-updates",
        ],
    }


@app.get("/api/pc-status")
def get_pc_status() -> List[Dict[str, Any]]:
    return load_pc_status_rows()


@app.post("/api/user-ids/issue", response_model=UserIdIssueResponse)
def post_issue_user_id(request: UserIdIssueRequest) -> UserIdIssueResponse:
    with USER_ID_STATE_LOCK:
        result = issue_user_id(request.preferred_user_id)
        save_user_id_state()

    return UserIdIssueResponse(
        user_id=result["user_id"],
        strategy=result["strategy"],
        issued_at=time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),
        source=request.source,
    )


@app.post("/api/user-ids/pool", response_model=UserIdPoolUpdateResponse)
def post_update_user_id_pool(request: UserIdPoolUpdateRequest) -> UserIdPoolUpdateResponse:
    incoming: List[str] = []
    seen: Set[str] = set()
    invalid_ids: List[str] = []
    for raw in request.user_ids:
        user_id = clean_user_id(raw)
        if not user_id:
            invalid_ids.append(str(raw))
            continue
        if user_id in seen:
            continue
        seen.add(user_id)
        incoming.append(user_id)

    if invalid_ids:
        raise HTTPException(
            status_code=400,
            detail={
                "message": "All user_ids must be exactly 10 digits",
                "invalid_user_ids": invalid_ids,
            },
        )

    with USER_ID_STATE_LOCK:
        if request.replace:
            USER_ID_STATE["pool"] = list(incoming)
        else:
            existing_pool = USER_ID_STATE.get("pool", [])
            existing_set = set(existing_pool)
            for user_id in incoming:
                if user_id not in existing_set:
                    existing_pool.append(user_id)
                    existing_set.add(user_id)
            USER_ID_STATE["pool"] = existing_pool

        save_user_id_state()
        pool_size = len(USER_ID_STATE.get("pool", []))

    return UserIdPoolUpdateResponse(
        pool_size=pool_size,
        accepted_count=len(incoming),
        replaced=bool(request.replace),
    )


@app.websocket("/ws/pc-updates")
async def websocket_pc_updates(websocket: WebSocket):
    await websocket.accept()

    try:
        while True:
            payload = {
                "type": "pc_status",
                "generated_at": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),
                "data": load_pc_status_rows(),
            }
            await websocket.send_json(payload)
            await asyncio.sleep(1.0)
    except WebSocketDisconnect:
        return


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("api:app", host="10.109.38.231", port=8000, reload=False)